#                          ....
#               .:=#@@@@@@@@@@@@@@@@@#=:.
#             .#@@@@@@@@@@@@@@@@@@@@@@@@@%:
#             #@@@@@@@@@@@@@@@@@@@@@@@@@@@%
#            -@@@%+==+#@@@@@@@@@@@*=--+%@@@=
#            *@*%@@+-.-. -@@@@@=..-::+@@%*@#
#           .%@@@@@@@@%-:*@@@@@*::%@@@@@@@@@.
#           .@@@@*-..-#@@.+@@@%+@@#:. :*@@@@.           developed by soc1ly
#           .@%. ......:+-.@@@@@*::::::::-=*.            (t.me/javacrime)
#           .%@@@@@@@@@@@:.@@@@@@@@@@@@@@@@@.
#            .%@@@@@@@@@% .@@@@@@@@@@@@@@@@#.             any questions?
#            -+-#@@@%%%=  .@@@@#*@@@@@@@@*=           write to me via telegram
#             =++:+@@@#-@.=@@@@@@%@@@@--===
#             .+%=:.:*@@@+-@@%-%@@@@=.=++*.
#               :@--#-..  .#@:    ..*#.#=
#                :%#..#@@@@@@@@@@@@@%+@-
#                  +%.%@@@=   *@@@@##*
#                   :%#@@@#  :@@@@@@-
#                     =@@@-.. #@@@+
#                      .*@#  -@@*.
#                         .  ..

reload: '&aКонфигурация успешно перезагружена! '
noperm: '&cУ вас нет прав на использование этой команды!'
use: '&cИспользование: /sjt reload'

title: '&aПриветствуем!'
subtitle: '&7Это сообщение, которое появляется при входе на сервер'
